[package]
name = "servicepoint-cli"
version = "0.1.0"
edition = "2021"
rust-version = "1.78.0"

[dependencies]
servicepoint = { version = "0.13.0", features = ["protocol_websocket"] }
clap = { version = "4.5", features = ["derive"]}
env_logger = "0.11"
log = "0.4"
